### ISSUE TITLE
GoModifyTags doesn't work if a tag contains malformed tags

### ISSUE THREAD

**Issue by fatih** [fatih/gomodifytags#19]
```
$ cat demo.go
package main

type Example struct {
	StatusID int64 `json:"status_id`
	Foo      string
	Bar      bool

	Server struct {
		Address string
		TLS     bool
	}

	DiskSize int64
	Volumes  []string
}
$ gomodifytags --file demo.go -struct Example -add-tags json
bad syntax for struct tag value
```

Here the struct tag is missing a quote. Two things we need to improve:

1. Error message should contain the struct name and the line position
2. We should modify other fields expect the malformed, instead of failing direclty

**Comment by viguza** [comment]
Hi @fatih, I have been messing around with this repo and also with https://github.com/fatih/structtag, and I also noticed this issue.

I was about to do my contribution with the 2 improvements you suggested, but then I got stuck. Right now if the tag can't be parsed the error is just returned and the next fields are ignored. However, if you continue with the other fields instead of failing directly, it's possible to find more fields with malformed tags, which is going to generate more errors.

As I see it, there are 2 ways to handle that:

1. Return an array of errors, where each error represents a malformed tag. Then, on `main` just loop that array and print each message on a new line.

2. Generate a big single error message with all the malformed tags lines and continue returning just a single error.

IMHO, the first option looks much better than the second one. I just wanted to know if you have any other possible solution in mind to tackle this?

**Comment by fatih** [comment]
@viguza Thank for looking into this. I had alrady some changes in my local branch as I think it's kinda hard to get it right. The current implementation continues to process all fields but returns a list of errors if the format mode is set to `json`.
