### ISSUE TITLE
Parsing fails for test files with -modified flag

### ISSUE THREAD

**Issue by ramya-rao-a** [fatih/gomodifytags#8]
While trying to run `gomodifytags` with `-modified` flag on a test file, we get the below error:

"failed to parse -modified archive: parsing size of archive file .: strconv.ParseUint: parsing "}": invalid syntax"

**Comment by fatih** [comment]
Hi @ramya-rao-a 

How we exactly are you using it? The `-modified` tries to read from stdin and the format is in form of:

```
// The archive consists of a series of files. Each file consists of a
// name, a decimal file size and the file contents, separated by
// newlinews. No newline follows after the file contents.
```

/cc @zmb3

**Comment by zmb3** [comment]
It seems you're just feeding the file in directly instead of using the [archive format](https://github.com/fatih/gomodifytags#unsaved-files).
We ultimately decided on this format for consistency with other tools (guru and gogetdoc, for example).

Since you have support for gogetdoc, you may already have code to build this archive, but if not, here's an example: https://github.com/joefitzgerald/go-plus/blob/master/lib/guru-utils.js#L8

**Comment by ramya-rao-a** [comment]
@fatih @zmb3 That's exactly how I have been using the `-modified` flag, and it works like a charm in all the files I was testing, but when I tried on one of the test files, it failed with the parsing error.

I digged a bit more and found that it is not the issue with the file being a test file, but with parsing of certain kinds of code.

Try it on https://github.com/golang/example/blob/master/stringutil/reverse_test.go and you will get the same error

**Comment by ramya-rao-a** [comment]
Ah! my bad.

My test file had some chinese characters and I was using a simple length function to get the file size.
Using `Buffer.byteLength` fixed the issue.

It worked like a charm with all the other files, so I was stumped.

False alarm.

Thanks!
