### ISSUE TITLE
anonymous structs?

### ISSUE THREAD

**Issue by braindev** [fatih/gomodifytags#9]
Is there support for anonymous structs?  `gomodifytags` doesn't seem to work on anonymous structs.

Here's an example:

Running `gomodifytags -file main.go -line 7,9 -add-tags json` returns `selection is not inside a struct`

```go
package main

import "fmt"

func main() {
	anon := []struct {
		ID int
		A  string
		B  string
	}{}

	fmt.Println(anon)
}
```

**Comment by fatih** [comment]
Hi @braindev 

Is there a use case for anon structs? Usually it's just for quick mocking and people don't use this a lot. The reason I've didn't implemented it back then was because  I've didn't see any use case for it. I know you can add tags for this as well. I'll leave this open for now, if I have time I'll tackle it (or if someone else wants to tackle this please let me know)

**Comment by braindev** [comment]
@fatih my case for anonymous structs is when I'm using a library like (like sqlx for example) and I want to serialize a result from a database query to JSON in a way that won't be used anywhere else in the app I'm working on.

something like this:

```go
cars := []struct {
  Year int     `json:"year"`
  Make string  `json:"make"`
  Model string `json: "model"`
}{}
err = db.Select(&cars, `select year, make, model from cars where ...`)
```

It's not the common case but when I upgraded my `vim-go` which uses `gomodifytags` I noticed I couldn't just add tags so that's why I asked.

Thanks for your awesome open source software!

**Comment by fatih** [comment]
Hm, seems like my latest push already fixed it :) What a great side effect. Can you just rebuild `gomodifytags` and try again? Because it works for me perfectly

**Comment by braindev** [comment]
Works perfectly.  Thanks!

**Comment by fatih** [comment]
Great, thanks @braindev for the feedback :)
